name: Deploy Vinograd Website

on:
  push:
    branches: [master]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@master     

      -name: install and build
        run: |
          npm install
          npm run generate

      -name: Deploy
        uses: JamesIves/github-pages-deploy-action@release/3.7.1
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          REPOSITORY_NAME: git@github.com:miklavcj/vinogradi.git
          VINOGRADI_ACCESS: ${{ secrets.VINOGRADI_ACCESS}}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true