name: Deploy Vinograd Website

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean Install dependencies and Build
        run: |
          npm install
          npm run generate
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          REPOSITORY_NAME: git@github.com:miklavcj/vinogradi.git
          VINOGRADI_ACCESS: ${{ secrets.VINOGRADI_ACCESS}}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
